#166726242 buyer should be able to update purchase order
breezycloud/automart pull request #4
Opened 2019-06-17 08:48 UTC by breezycloud

PATCH request: update purchase order

This feature should allow the buyer to update purchase order

This feature can be tested using POSTMAN

![image](https://user-images.githubusercontent.com/38924174/59589661-bb432e80-90ea-11e9-906d-c50c1a280650.png)

[#166726242 ](https://www.pivotaltracker.com/story/show/166726242)

2019-06-17 09:41 UTC, TheoOkafor requested changes
The build is failing on Travis. Make sure that build passes before you merge

2019-06-17 09:41 UTC, TheoOkafor commented on API/test/order.js
> +var expect  = require('chai').expect;
Use ES6 syntax

2019-06-18 00:24 UTC, breezycloud commented on API/test/order.js
> +var expect  = require('chai').expect;
Fixed.

2019-06-18 02:42 UTC, TheoOkafor approved these changes
Good!

2019-06-18 06:04 UTC, merged